### ISSUE TITLE
Audio only comes out of right speaker.

### ISSUE THREAD

**Issue by davisdude** [TannerRogalsky/love.js#12]
This may be related to issue #8, but if you use headphones you can tell audio only works on one ear.

**Comment by TannerRogalsky** [comment]
This is definitely an issue that I'm experiencing as well. Doesn't seem to relate to the source being mono or stereo. Or even the source format. This needs more research. Maybe an issue with the position of the audio.

**Comment by TannerRogalsky** [comment]
This should be fixed as of 16288c2.

**Comment by davisdude** [comment]
Did you update the demos? Because they still have this problem.

**Comment by TannerRogalsky** [comment]
I didn't update the demos.
